name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: current
    - run: npm install
    - name: Build the site with parcel
      run: npx parcel build index.html --public-url "https://jonathanlindsey.github.io/learn_html_css_ts/"
    - name: Deploy to GitHub Pages
      # Getting this error from GitHub Actions "fatal: could not read Username for 'https://github.com': No such device or address"
      # run: |
      #   git config user.email ""
      #   git config user.name "CI"
      #   npx gh-pages -d dist

      # This works but don't really want to use an unofficial GitHub Action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
